# Generated by Django 3.2.15 on 2022-09-21 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drug_dose', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('route', models.CharField(blank=True, max_length=8)),
                ('animal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.record')),
                ('drug', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='prescriptions.drugs')),
                ('vet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
