# Generated by Django 3.2.15 on 2022-09-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='measure',
            field=models.CharField(choices=[('ML', 'ml'), ('MG', 'mg')], max_length=2),
        ),
    ]
