# Generated by Django 3.2.15 on 2022-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_auto_20221006_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='high_dose',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Add high dose for tablets                                     only.', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='tablet_strength',
            field=models.CharField(blank=True, help_text='Add tablet strength in                                        numbers, separated by commas.', max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='warnings',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
