# Generated by Django 3.2.15 on 2022-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, choices=[('No Repeat', 'No Repeat'), ('SID', 'SID'), ('BID', 'BID'), ('TID', 'TID')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='length',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
