# Generated by Django 3.2.15 on 2022-10-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('name', 'surname', 'date_of_birth', 'species', 'sex')},
        ),
    ]
