# Generated by Django 3.2.15 on 2022-09-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['surname']},
        ),
    ]
