# Generated by Django 3.2.15 on 2022-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
