# Generated by Django 3.2.15 on 2022-09-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
