# Generated by Django 3.2.15 on 2022-09-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetprofiles', '0003_alter_vet_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
